-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.course DROP CONSTRAINT IF EXISTS course_instructor;

ALTER TABLE IF EXISTS public.instructor DROP CONSTRAINT IF EXISTS instructor_detail;

ALTER TABLE IF EXISTS public.review DROP CONSTRAINT IF EXISTS course_review;

ALTER TABLE IF EXISTS public.course_student DROP CONSTRAINT IF EXISTS course;

ALTER TABLE IF EXISTS public.course_student DROP CONSTRAINT IF EXISTS student;



DROP TABLE IF EXISTS public.course;

CREATE TABLE IF NOT EXISTS public.course
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    instructor_id integer,
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT course_name UNIQUE (title)
);

DROP TABLE IF EXISTS public.instructor;

CREATE TABLE IF NOT EXISTS public.instructor
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    instructor_detail_id integer,
    CONSTRAINT instructor_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.instructor_detail;

CREATE TABLE IF NOT EXISTS public.instructor_detail
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    youtube_channel text COLLATE pg_catalog."default",
    hobby text COLLATE pg_catalog."default",
    CONSTRAINT instructor_detail_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.review;

CREATE TABLE IF NOT EXISTS public.review
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment text COLLATE pg_catalog."default",
    course_id integer,
    CONSTRAINT review_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.course_student;

CREATE TABLE IF NOT EXISTS public.course_student
(
    course_id integer NOT NULL,
    student_id integer NOT NULL,
    CONSTRAINT course_student_pkey PRIMARY KEY (course_id, student_id)
);

DROP TABLE IF EXISTS public.student;

CREATE TABLE IF NOT EXISTS public.student
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    CONSTRAINT student_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.course
    ADD CONSTRAINT course_instructor FOREIGN KEY (instructor_id)
    REFERENCES public.instructor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.instructor
    ADD CONSTRAINT instructor_detail FOREIGN KEY (instructor_detail_id)
    REFERENCES public.instructor_detail (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT course_review FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_student
    ADD CONSTRAINT course FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_student
    ADD CONSTRAINT student FOREIGN KEY (student_id)
    REFERENCES public.student (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;