services:
  redis-stack:
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    image: redis/redis-stack:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  rabbitmq:
    hostname: my-rabbit
    container_name: some-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Welcome@123
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  db-portgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - PGUSER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  db-mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=my_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  postgresql_data:
    external: true
  mysql_data:
    external: true
